program/program/urls.py
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path
from center import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('profile/', views.profile, name='profile'),
    path('profile/pass/', views.changePass, name='pass'),
    path('profile/deleteUser/', views.deleteUser, name='deleteUser'),
    path('listPractices/', views.listPractices, name='listPractices'),
    path('listPractices/createPractice/', views.createPractice, name='createPractice'),
    path('listPractices/createPractice/practice/<int:pk>/', views.practice, name='practice'),
    path('listPractices/createPractice/practice/<int:pk>/validationPractice/', views.validationPractice, name='validationPractice'),
    path('listPractices/createPractice/generation', views.generationPractice, name='generationPractice'),
    path('createClass/', views.createClass, name='createClass'),
    path('listCalassrooms/', views.listCalassrooms, name='listCalassrooms'),
    path('listCalassrooms/validCode/', views.validCode, name='validCode'),
    path('listCalassrooms/<str:name>/', views.classroom, name='classroom'),
    path('listCalassrooms/<str:name>/members/', views.members, name='members'),
    path('listCalassrooms/<str:name>/listExam/', views.listExam, name='listExam'),
    path('listCalassrooms/<str:name>/listHomework/', views.listHomework, name='listHomework'),
    path('listCalassrooms/<str:name>/listExam/createExam/', views.createExam, name='createExam'),
    path('listCalassrooms/<str:name>/listHomework/createHomework/', views.createHomework, name='createHomework'),
    path('listCalassrooms/<str:name>/generationWork/', views.generationWork, name='generationWork'),
    path('listCalassrooms/<str:name>/listHomework/<str:name_work>/', views.work, name='workHomework'),
    path('listCalassrooms/<str:name>/listExam/<str:name_work>/', views.work, name='workExam'),
    path('listCalassrooms/<str:name>/listHomework/<str:name_work>/homework/', views.homeworkOrExam, name='homework'),
    path('listCalassrooms/<str:name>/listExam/<str:name_work>/exam/', views.homeworkOrExam, name='exam'),
    path('listCalassrooms/<str:name>/listHomework/<str:name_work>/homework/valid/', views.validHomeworkOrExam, name='homework'),
    path('listCalassrooms/<str:name>/listExam/<str:name_work>/exam/valid/', views.validHomeworkOrExam, name='exam'),
    path('listCalassrooms/<str:name>/listHomework/<str:name_work>/viewAnswer/<str:student_id>', views.viewAnswer, name='viewAnswer'),
    path('listCalassrooms/<str:name>/listExam/<str:name_work>/viewAnswer/<str:student_id>', views.viewAnswer, name='viewAnswer'),
    path('listCalassrooms/<str:name>/listHomework/<str:name_work>/homework/viewAnswer/<str:student_id>', views.viewAnswer, name='viewAnswer'),
    path('listCalassrooms/<str:name>/listExam/<str:name_work>/homework/viewAnswer/<str:student_id>', views.viewAnswer, name='viewAnswer'),
    path('listCalassrooms/<str:name>/listHomework/<str:name_work>/editWorkHome/', views.editHomeworkOrExam, name='editWorkHome'),
    path('listCalassrooms/<str:name>/listExam/<str:name_work>/editWorkExam/', views.editHomeworkOrExam, name='editWorkExam'),
    path('listCalassrooms/<str:name>/listExam/<str:name_work>/editWorkExam/deleteExam/', views.deleteHomeworkOrExam, name='deleteExam'),
    path('listCalassrooms/<str:name>/listHomework/<str:name_work>/editWorkHome/deleteHome/', views.deleteHomeworkOrExam, name='deleteHome'),
    path('listCalassrooms/<str:name>/profileClass/', views.profileClass, name='profileClass'),
    path('listCalassrooms/<str:name>/profileClass/deleteClass/', views.deleteClass, name='deleteClass'),
    path('listCalassrooms/<str:name>/delete/', views.deleteStudent, name='deleteStudent'),
    path('register/', views.RegisterUser, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
] 

if settings.DEBUG:       
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

program/center/models.py
import time
from datetime import datetime
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='default.jpg', upload_to='profile_pics')
    # Funcion para que se mestre en la parte de admistarador el nombre de usuario en ves de tener el nombre de objeto
    def __str__(self):
        return f'{self.user.username} Profile'

class TypeClass(models.Model):
    name = models.CharField(max_length=50)

class Classes(models.Model):
    name = models.CharField(max_length=200)
    codes = models.CharField(max_length=20, unique = True)
    teacher = models.ForeignKey(User, blank=True, related_name='teacher', default=None, on_delete=models.CASCADE)
    type_c = models.ForeignKey(TypeClass, null=True, default=None, on_delete=models.CASCADE)

class Classrooms(models.Model):
    teacher = models.ForeignKey(User, blank=True, related_name='teachers', default=None, on_delete=models.CASCADE)
    student = models.ForeignKey(User, blank=True, related_name='students', default=None, on_delete=models.CASCADE)
    classess = models.ForeignKey(Classes, null=True, default=None, on_delete=models.CASCADE)

class TypeActivity(models.Model):
    name = models.CharField(max_length=50)

class WorkActivity(models.Model):
    name_work = models.CharField(max_length=50)
    type_a = models.ForeignKey(TypeActivity, null=True, default=None, on_delete=models.CASCADE)
    start_date = models.DateField(default=timezone.now().strftime("%Y-%m-%d"))
    finish_date = models.DateField()
    classess = models.ForeignKey(Classes, null=True, default=None, on_delete=models.CASCADE)
    # Funcion para determinar un limite de fecha entre la fecha de inicio y fin para resolver los problemas de tarea o examen
    def active(self):
        now = timezone.now().strftime("%Y-%m-%d")
        date_object = datetime.strptime(now, "%Y-%m-%d" ).date()
        if self.start_date <= date_object and date_object <= self.finish_date:
            return True
        return False

class OperationGenerate(models.Model):
    quantity = models.IntegerField()
    size = models.IntegerField(blank=True, null=True, default=None)
    propSim = models.IntegerField(blank=True, null=True, default=None)
    maxProf = models.IntegerField(blank=True, null=True, default=None)
    operation = models.CharField(max_length=10, blank=True, null=True, default=None)
    additional = models.CharField(max_length=10, blank=True, null=True, default=None)
    work_activity = models.ForeignKey(WorkActivity, null=True, default=None, on_delete=models.CASCADE)

class AveragesWorkActivity(models.Model):
    average = models.IntegerField()
    student = models.ForeignKey(User, blank=True, related_name='studentWork', null=True, default=None, on_delete=models.CASCADE)
    type_a = models.ForeignKey(WorkActivity, null=True, default=None, on_delete=models.CASCADE)
    active = models.BooleanField(null=True, default=False, blank=True)

class OperationsPractics (models.Model):
    title = models.CharField(max_length=50)
    formula = models.CharField(max_length=225)
    results = models.CharField(max_length=511)
    aux = models.CharField(max_length=225, null=True, blank=True)
    your_results = models.CharField(max_length=225, null=True, blank=True)
    validation = models.CharField(max_length=20, null=True, blank=True)
    users = models.ForeignKey(User, blank=True, related_name='user', default=None, on_delete=models.CASCADE)
    type_c = models.ForeignKey(TypeClass, null=True, default=None, on_delete=models.CASCADE)

class OperationsWorkActivity (models.Model):
    title = models.CharField(max_length=50)
    formula = models.CharField(max_length=225)
    results = models.CharField(max_length=511)
    aux = models.CharField(max_length=225, null=True, blank=True)
    validation = models.CharField(max_length=20, null=True, blank=True)
    your_results = models.CharField(max_length=225, null=True, blank=True)
    users = models.ForeignKey(User, blank=True, related_name='studentOpeWork', default=None, on_delete=models.CASCADE)
    work = models.ForeignKey(WorkActivity, null=True, default=None, on_delete=models.CASCADE)

class Comments(models.Model):
    user_comment = models.ForeignKey(User, blank=True, related_name='users', default=None, on_delete=models.CASCADE)
    time = models.CharField(max_length=50, default=timezone.now().strftime("%a %b %d %Y, %H:%M:%S"))
    text = models.TextField()
    classess = models.ForeignKey(Classes, null=True, default=None, on_delete=models.CASCADE)
    # Funcion para que es puedan guandar archivos de texto grande en la base de datos
    def __str__(self):
        return self.text

program/center/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, PasswordChangeForm
from .models import Profile

# La base de los datos que pide para agragar un nuevo usuario
class RegisterForm(UserCreationForm):
    email = forms.EmailField()
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'username', 'email', 'password1', 'password1']
        labels = {'first_name': 'Fist Name', 'last_name': 'Last Name', 'username': 'No. Control', 'email': 'Email', 'password1': 'Password', 'password1': 'Confirm Password'}
    
    # Funcion para detectar si existe un usuario con el mismo nombre
    def clean_username(self):
        username = self.cleaned_data['username'].lower()
        r = User.objects.filter(username=username)
        if r.count():
            raise  ValidationError("Username already exists")
        return username

    # Funcion para detectar si existe un usurio con el mismo correo electronico
    def clean_email(self):
        email = self.cleaned_data['email'].lower()
        r = User.objects.filter(email=email)
        if r.count():
            raise  ValidationError("Email already exists")
        return email

# La base de los datos que pide para actualizar datos personales
class UserUpdateFrom(forms.ModelForm):
    email = forms.EmailField()
    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email']
        labels = {'username': 'Username', 'first_name': 'Fist Name', 'last_name': 'Last Name', 'email': 'Email'}

# La base de los datos que pide para actualizar la foto del usuario
class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['image']
        
# La base de los datos que pide para actualizar la contraseña 
class PasswordUpdateFrom(PasswordChangeForm):
    class Meta:
        model = User
        fields = ['old_password', 'new_password1', 'new_password2']

program/center/templates/rooms/chageClass.html
{% extends "static/base.html" %}
{% block title %} Editar Clase {% endblock %}
{% block content %}
<div class="bg-white border rounded py-3 px-5">
  <legend><b>{{name}}</b></legend>
  <div class="list-group list-group-horizontal">
    <a
      href="/listCalassrooms/{{name}}/"
      class="list-group-item list-group-item-info list-group-item-action text-dark"
    >
      Mensajes
    </a>
    <a
      href="/listCalassrooms/{{name}}/members/"
      class="list-group-item list-group-item-info list-group-item-action text-dark"
    >
      Miembros
    </a>
    <a
      href="/listCalassrooms/{{name}}/listHomework/"
      class="list-group-item list-group-item-info list-group-item-action text-dark"
    >
      Tareas
    </a>
    <a
      href="/listCalassrooms/{{name}}/listExam/"
      class="list-group-item list-group-item-info list-group-item-action text-dark"
    >
      Examenes
    </a>

    {% if perms.center.add_classes %}
    <a
      href="/listCalassrooms/{{name}}/profileClass/"
      class="list-group-item list-group-item-info list-group-item-action active"
    >
      Detalles de la Clase
    </a>
    {% elif perms.center.add_classrooms %}
    <a
      href="delete/"
      onclick="return deleten()"
      class="list-group-item list-group-item-primary list-group-item-action"
    >
      Salir de la clase
    </a>
    {% endif %}
  </div>
  <hr />

  <legend>Detalles de la clase</legend>

  <div>
    <div class="container-fluid">
      <form method="POST">
        {% csrf_token %}
        <div class="form-group text-left">
          <label>Nombre:</label>
          <input
            type="text"
            class="form-control"
            name="changeName"
            value="{{class.name}}"
            placeholder="Inserta el nombre de la clase..."
            required
          />
        </div>
        <button
          type="submit"
          name="accept"
          class="px-4 btn badge-pill btn-primary"
        >
          Cambiar nombre
        </button>
      </form>
      <hr />
      <a href="/listCalassrooms/{{name}}/profileClass/deleteClass/">
        <button
          type="submit"
          name="accept"
          class="px-4 btn badge-pill btn-danger"
        >
          Eliminar clase
        </button>
      </a>
    </div>
  </div>
</div>
{% endblock %}

program/center/templates/rooms/classroom.html
{% extends "static/base.html" %}
{% block title %} Salon de clases {% endblock %}
{% block content %}

<div class="bg-white border rounded py-3 px-5">
  <legend><b>{{n}}</b></legend>
  <div class="list-group list-group-horizontal">
    <a
      href="members/"
      class="list-group-item list-group-item-info list-group-item-action active"
    >
      Mensajes
    </a>
    <a
      href="members/"
      class="list-group-item list-group-item-info list-group-item-action text-dark"
    >
      Miembros
    </a>
    <a
      href="listHomework/"
      class="list-group-item list-group-item-info list-group-item-action text-dark"
    >
      Tareas
    </a>
    <a
      href="listExam/"
      class="list-group-item list-group-item-info list-group-item-action text-dark"
    >
      Examenes
    </a>

    {% if perms.center.add_classes %}
    <!-- <a
      href="profileClass/"
      class="list-group-item list-group-item-info list-group-item-action text-dark"
    >
      Detalles de la Clase
    </a> -->
    {% elif perms.center.add_classrooms %}
    <!-- <a
      href="delete/"
      onclick="return deleten()"
      class="list-group-item list-group-item-primary list-group-item-action active"
    >
      Salir de la clase
    </a> -->
    {% endif %}
  </div>
  <hr />

    <legend>Mensajes:</legend>
    {% if com %}
        {% for c in com %}
        <div class="alert alert-secondary text-left" role="alert">
          <img
              class="rounded-circle"
              src="{{c.user_comment.profile.image.url}}"
              width="25"
              height="25"
              alt="{{c.user_comment.username}}_ProfileImg"
            /> 
            <b>{{c.user_comment.username}}</b> - {{c.time}}
          <hr>
          <div class="container">
            {{c.text}}
          </div>
        </div>
        {% endfor %}
    {% else %}<b>Sin comentarios</b>{% endif %}
    <hr />
    <form method="POST">
      {% csrf_token %}
      <div class="form-group text-left">
        <label>Nuevo mensaje:</label>
        <textarea
          class="form-control"
          name="msj"
          rows="3"
          placeholder="Comentar..."
        ></textarea>
      </div>
      <button class="px-4 btn badge-pill btn-success" type="submit">
        Enviar
      </button>
    </form>
    
  <script type="text/javascript">
    function deleten() {
      var x = confirm("want delete your user ?");
      if (x) return true;
      else return false;
    }
  </script>
</div>
{% endblock %}

program/center/templates/rooms/createClass.html
{% extends "static/base.html" %}
{% block title %}
Crear Clase
{% endblock %}
{% block content %}

<div class="bg-white border rounded py-3 px-5">
  <legend><b>Crear nueva clase</b></legend>
  <form method="POST" class="">
    {% csrf_token %}

    <div class="form-group text-left">
      <label>Tipo de clase:</label>
      <select class="form-control" name="tip">
        {% for t in query %}
        <option value="{{t.id}}">{{t.name}}</option>
        {% endfor %}
      </select>
    </div>

    <div class="form-group text-left">
      <label>Nombre de la clase:</label>
      <input name="nameClass" type="text" class="form-control" placeholder="Inserta el nombre de la clase..." required/>
    </div>

    <button type="submit" class="px-4 btn badge-pill btn-info">Aceptar</button>
  </form>
</div>
{% endblock %}

program/center/templates/rooms/listClassrooms.html
{% extends "static/base.html" %}
{% block title %} Lista de clases {% endblock %}
{% block content %}

<div class="bg-white border rounded py-3 px-5">
  <div class="container"><div class="row">
  <div class="col-7 text-right h1"><b>Lista de clases:</b></div>
  <div class="col-5 text-left align-top">
  {% if perms.center.add_classes %}
  <a  class="nav-link" href="{% url 'createClass' %}">
    <button 
      type="button" 
      class="mb-3 px-4 btn badge-pill btn-info"
    >
      <svg xmlns="http://www.w3.org/2000/svg" width="2rem" height="2rem" fill="currentColor" class="bi bi-plus" viewBox="0 0 16 16">
  <path d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4z"/></svg>
    </button>
  </a>
  
  {% elif perms.center.add_classrooms %}
  <button
    type="button"
    class="mb-3 px-4 btn badge-pill btn-info"
    data-toggle="modal"
    data-target="#staticBackdrop"
  >
    <svg xmlns="http://www.w3.org/2000/svg" width="2rem" height="2rem" fill="currentColor" class="bi bi-plus" viewBox="0 0 16 16">
  <path d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4z"/></svg>
  </button>
  
  {% endif %}
  </div>
  </div></div>
  <hr/>
  {% if query %}
  <table class="table border table-striped">
    <thead class="thead-dark">
      <tr style="font-size: 30px">
        <th>Clase</th>
        {% if perms.center.add_classes %}
        <th>Código</th>
        {% elif perms.center.add_classrooms %}
        <th>Materia</th>
        {% endif %}
      </tr>
    </thead>
    <tbody>
      {% for c in query %}
      {% if perms.center.add_classes %}
      <tr style="font-size: 20px">
        <td>
          <a href="{% url 'classroom' c.name %}" class="text-primary">
            <b>{{c.name}}</b>
          </a>
        </td>
        <td>{{c.codes}}</td>
        {% elif perms.center.add_classrooms %}
        <td>
          <a href="{% url 'classroom' c.classess.name %}" class="text-primary">
            <b>{{c.classess.name}}</b>
          </a>
        </td>
        <td>{{c.classess.type_c.name}}</td>
        {% endif %}
      </tr>
      {% endfor %}
    </tbody>
  </table>
  {% else %}
  <hr />
  <legend>No hay practicas</legend>
  {% endif %}
</div>

{% if perms.center.add_classrooms %}
<!-- Modal -->
<div
  class="modal fade"
  id="staticBackdrop"
  data-backdrop="static"
  data-keyboard="false"
  tabindex="-1"
  aria-labelledby="staticBackdropLabel"
  aria-hidden="true"
>
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <form action="{% url 'validCode' %}" method="post">
        <div class="modal-header">
          <h5 class="modal-title" id="staticBackdropLabel">
            Agregar Nueva Clase
          </h5>
          <button
            type="button"
            class="close"
            data-dismiss="modal"
            aria-label="Close"
          >
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          {% csrf_token %}
          <div class="form-group text-left">
            <label>Codigo de la clase:</label>
            <input
              type="text"
              name="classIns"
              class="form-control"
              placeholder="Inserta el código de la clase..."
            />
          </div>
        </div>
        <div class="modal-footer">
          <button
            type="button"
            class="px-4 btn badge-pill btn-danger"
            data-dismiss="modal"
          >
            Cancelar
          </button>
          <button type="submit" class="px-4 btn badge-pill btn-success">
            Agregar
          </button>
        </div>
      </form>
    </div>
  </div>
</div>
{% endif %}
{% endblock %}

program/center/templates/rooms/listExam.html
{% extends "static/base.html" %}
{% block title %} Lista de Examenes {% endblock %}
{% block content %}

<div class="bg-white border rounded py-3 px-5">
  <legend><b>{{n}}</b></legend>
  <div class="list-group list-group-horizontal">
    <a
      href="/listCalassrooms/{{n}}/"
      class="list-group-item list-group-item-info list-group-item-action text-dark"
    >
      Mensajes
    </a>
    <a
      href="/listCalassrooms/{{n}}/members/"
      class="list-group-item list-group-item-info list-group-item-action text-dark"
    >
      Miembros
    </a>
    <a
      href="/listCalassrooms/{{n}}/listHomework/"
      class="list-group-item list-group-item-info list-group-item-action text-dark"
    >
      Tareas
    </a>
    <a
      href="/listCalassrooms/{{n}}/listExam/"
      class="list-group-item list-group-item-info list-group-item-action active"
    >
      Examenes
    </a>

    {% if perms.center.add_classes %}
    <!-- <a
      href="/listCalassrooms/{{n}}/profileClass/"
      class="list-group-item list-group-item-info list-group-item-action text-dark"
    >
      Detalles de la Clase
    </a> -->
    {% elif perms.center.add_classrooms %}
    <!-- <a
      href="delete/"
      onclick="return deleten()"
      class="list-group-item list-group-item-primary list-group-item-action active"
    >
      Salir de la clase
    </a> -->
    {% endif %}
  </div>
  <hr />

  <div class="container"> <div class="row">
  <div class="col-7 text-right h3"><b>Lista de Examenes</b></div>
  <div class="col-5 text-left">
  {% if perms.center.add_classes %}
  <a href="createExam/">
    <button type="button" class="mb-3 px-4 btn badge-pill btn-info text-left">
      Crear Examen
    </button>
  </a>
  {% endif %}
  </div></div> </div>
  <div class="container">
    {% if list %}
    {% for l in list %}
    <div class="alert alert-secondary text-left" role="alert">
      <a
        href="/listCalassrooms/{{n}}/listExam/{{l.name_work}}"
        class="text-dark"
      >
        <b>{{l.name_work}}</b>
      </a>
      <hr />
      <small class="container">
        Esta tarea se entrga antes de la fecha <i>{{l.finish_date}}</i>
      </small>
    </div>
    {% endfor %}
    {% else %}
    <b>No hay tareas</b>
    {% endif %}
  </div>
</div>
{% endblock %}

program/center/templates/rooms/listHomework.html
{% extends "static/base.html" %}
{% block title %} Lista de Tareas {% endblock %}
{% block content %}

<div class="bg-white border rounded py-3 px-5">
  <legend><b>{{n}}</b></legend>
  <div class="list-group list-group-horizontal">
    <a
      href="/listCalassrooms/{{n}}/"
      class="list-group-item list-group-item-info list-group-item-action text-dark"
    >
      Mensajes
    </a>
    <a
      href="/listCalassrooms/{{n}}/members/"
      class="list-group-item list-group-item-info list-group-item-action text-dark"
    >
      Miembros
    </a>
    <a
      href="/listCalassrooms/{{n}}/listHomework/"
      class="list-group-item list-group-item-info list-group-item-action active"
    >
      Tareas
    </a>
    <a
      href="/listCalassrooms/{{n}}/listExam/"
      class="list-group-item list-group-item-info list-group-item-action text-dark"
    >
      Examenes
    </a>

    {% if perms.center.add_classes %}
    <!-- <a
      href="/listCalassrooms/{{n}}/profileClass/"
      class="list-group-item list-group-item-info list-group-item-action text-dark"
    >
      Detalles de la Clase
    </a> -->
    {% elif perms.center.add_classrooms %}
    <!-- <a
      href="delete/"
      onclick="return deleten()"
      class="list-group-item list-group-item-primary list-group-item-action active"
    >
      Salir de la clase
    </a> -->
    {% endif %}
  </div>
  <hr />
  <div class="container"> <div class="row">
  <div class="col-7 text-right h3"><b>Lista de Tareas</b></div>
  <div class="col-5 text-left">
  {% if perms.center.add_classes %}
  <a href="createHomework/">
    <button type="button" class="mb-3 px-4 btn badge-pill btn-info text-left">
      Crear Tarea
    </button>
  </a>
  {% endif %}
  </div></div> </div>
  <div class="container">
    {% if list %}
    {% for l in list %}
    <div class="alert alert-secondary text-left" role="alert">
      <a
        href="/listCalassrooms/{{n}}/listHomework/{{l.name_work}}"
        class="text-dark"
      >
        <b>{{l.name_work}}</b>
      </a>
      <hr />
      <small class="container">
        Esta tarea se entrga antes de la fecha <i>{{l.finish_date}}</i>
      </small>
    </div>
    {% endfor %}
    {% else %}
    <b>No hay tareas</b>
    {% endif %}
  </div>
</div>
{% endblock %}

program/center/templates/rooms/members.html
{% extends "static/base.html" %}
{% block title %} Miembros {% endblock %}
{% block content %}

<div class="bg-white border rounded py-3 px-5">
  <legend><b>{{n}}</b></legend>
  <div class="list-group list-group-horizontal">
    <a
      href="/listCalassrooms/{{n}}/"
      class="list-group-item list-group-item-info list-group-item-action text-dark"
    >
      Mensajes
    </a>
    <a
      href="/listCalassrooms/{{n}}/members/"
      class="list-group-item list-group-item-info list-group-item-action active"
    >
      Miembros
    </a>
    <a
      href="/listCalassrooms/{{n}}/listHomework/"
      class="list-group-item list-group-item-info list-group-item-action text-dark"
    >
      Tareas
    </a>
    <a
      href="/listCalassrooms/{{n}}/listExam/"
      class="list-group-item list-group-item-info list-group-item-action text-dark"
    >
      Examenes
    </a>

    {% if perms.center.add_classes %}
    <!-- <a
      href="/listCalassrooms/{{n}}/profileClass/"
      class="list-group-item list-group-item-info list-group-item-action text-dark"
    >
      Detalles de la Clase
    </a> -->
    {% elif perms.center.add_classrooms %}
    <!-- <a
      href="delete/"
      onclick="return deleten()"
      class="list-group-item list-group-item-primary list-group-item-action active"
    >
      Salir de la clase
    </a> -->
    {% endif %}
  </div>
  <hr />

  <legend>Lista de Miembros</legend>
  
  <table class="table border table-striped">
    <thead class="bg-secondary text-white">
      {% for t in tea %}
      <tr>
        <th>
          <img
            class="account-img rounded"
            src="{{t.teacher.profile.image.url}}"
            width="25"
            height="25"
            alt="Smiley face"
          />
        </th>
        <th>{{t.teacher.first_name}}</th>
        <th>{{t.teacher.last_name}}</th>
      </tr>
      {% endfor %}
    </thead>
    <tbody>
      {% if stu %}
      {% for s in stu %}
      <tr>
        <th>
          <img
            class="account-img rounded"
            src="{{s.student.profile.image.url}}"
            width="25"
            height="25"
            alt="Smiley face"
          />
        </th>
        <td>{{s.student.first_name}}</td>
        <td>{{s.student.last_name}}</td>
      </tr>
      {% endfor %}
      {% endif %}
    </tbody>
  </table>
</div>
{% endblock %}