program/program/urls.py
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path
from center import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('profile/', views.profile, name='profile'),
    path('profile/pass/', views.changePass, name='pass'),
    path('profile/deleteUser/', views.deleteUser, name='deleteUser'),
    path('listPractices/', views.listPractices, name='listPractices'),
    path('listPractices/createPractice/', views.createPractice, name='createPractice'),
    path('listPractices/createPractice/practice/<int:pk>/', views.practice, name='practice'),
    path('listPractices/createPractice/practice/<int:pk>/validationPractice/', views.validationPractice, name='validationPractice'),
    path('listPractices/createPractice/generation', views.generationPractice, name='generationPractice'),
    path('createClass/', views.createClass, name='createClass'),
    path('listCalassrooms/', views.listCalassrooms, name='listCalassrooms'),
    path('listCalassrooms/validCode/', views.validCode, name='validCode'),
    path('listCalassrooms/<str:name>/', views.classroom, name='classroom'),
    path('listCalassrooms/<str:name>/members/', views.members, name='members'),
    path('listCalassrooms/<str:name>/listExam/', views.listExam, name='listExam'),
    path('listCalassrooms/<str:name>/listHomework/', views.listHomework, name='listHomework'),
    path('listCalassrooms/<str:name>/listExam/createExam/', views.createExam, name='createExam'),
    path('listCalassrooms/<str:name>/listHomework/createHomework/', views.createHomework, name='createHomework'),
    path('listCalassrooms/<str:name>/generationWork/', views.generationWork, name='generationWork'),
    path('listCalassrooms/<str:name>/listHomework/<str:name_work>/', views.work, name='workHomework'),
    path('listCalassrooms/<str:name>/listExam/<str:name_work>/', views.work, name='workExam'),
    path('listCalassrooms/<str:name>/listHomework/<str:name_work>/homework/', views.homeworkOrExam, name='homework'),
    path('listCalassrooms/<str:name>/listExam/<str:name_work>/exam/', views.homeworkOrExam, name='exam'),
    path('listCalassrooms/<str:name>/listHomework/<str:name_work>/homework/valid/', views.validHomeworkOrExam, name='homework'),
    path('listCalassrooms/<str:name>/listExam/<str:name_work>/exam/valid/', views.validHomeworkOrExam, name='exam'),
    path('listCalassrooms/<str:name>/listHomework/<str:name_work>/viewAnswer/<str:student_id>', views.viewAnswer, name='viewAnswer'),
    path('listCalassrooms/<str:name>/listExam/<str:name_work>/viewAnswer/<str:student_id>', views.viewAnswer, name='viewAnswer'),
    path('listCalassrooms/<str:name>/listHomework/<str:name_work>/homework/viewAnswer/<str:student_id>', views.viewAnswer, name='viewAnswer'),
    path('listCalassrooms/<str:name>/listExam/<str:name_work>/homework/viewAnswer/<str:student_id>', views.viewAnswer, name='viewAnswer'),
    path('listCalassrooms/<str:name>/listHomework/<str:name_work>/editWorkHome/', views.editHomeworkOrExam, name='editWorkHome'),
    path('listCalassrooms/<str:name>/listExam/<str:name_work>/editWorkExam/', views.editHomeworkOrExam, name='editWorkExam'),
    path('listCalassrooms/<str:name>/listExam/<str:name_work>/editWorkExam/deleteExam/', views.deleteHomeworkOrExam, name='deleteExam'),
    path('listCalassrooms/<str:name>/listHomework/<str:name_work>/editWorkHome/deleteHome/', views.deleteHomeworkOrExam, name='deleteHome'),
    path('listCalassrooms/<str:name>/profileClass/', views.profileClass, name='profileClass'),
    path('listCalassrooms/<str:name>/profileClass/deleteClass/', views.deleteClass, name='deleteClass'),
    path('listCalassrooms/<str:name>/delete/', views.deleteStudent, name='deleteStudent'),
    path('register/', views.RegisterUser, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
] 

if settings.DEBUG:       
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

program/center/models.py
import time
from datetime import datetime
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='default.jpg', upload_to='profile_pics')
    # Funcion para que se mestre en la parte de admistarador el nombre de usuario en ves de tener el nombre de objeto
    def __str__(self):
        return f'{self.user.username} Profile'

class TypeClass(models.Model):
    name = models.CharField(max_length=50)

class Classes(models.Model):
    name = models.CharField(max_length=200)
    codes = models.CharField(max_length=20, unique = True)
    teacher = models.ForeignKey(User, blank=True, related_name='teacher', default=None, on_delete=models.CASCADE)
    type_c = models.ForeignKey(TypeClass, null=True, default=None, on_delete=models.CASCADE)

class Classrooms(models.Model):
    teacher = models.ForeignKey(User, blank=True, related_name='teachers', default=None, on_delete=models.CASCADE)
    student = models.ForeignKey(User, blank=True, related_name='students', default=None, on_delete=models.CASCADE)
    classess = models.ForeignKey(Classes, null=True, default=None, on_delete=models.CASCADE)

class TypeActivity(models.Model):
    name = models.CharField(max_length=50)

class WorkActivity(models.Model):
    name_work = models.CharField(max_length=50)
    type_a = models.ForeignKey(TypeActivity, null=True, default=None, on_delete=models.CASCADE)
    start_date = models.DateField(default=timezone.now().strftime("%Y-%m-%d"))
    finish_date = models.DateField()
    classess = models.ForeignKey(Classes, null=True, default=None, on_delete=models.CASCADE)
    # Funcion para determinar un limite de fecha entre la fecha de inicio y fin para resolver los problemas de tarea o examen
    def active(self):
        now = timezone.now().strftime("%Y-%m-%d")
        date_object = datetime.strptime(now, "%Y-%m-%d" ).date()
        if self.start_date <= date_object and date_object <= self.finish_date:
            return True
        return False

class OperationGenerate(models.Model):
    quantity = models.IntegerField()
    size = models.IntegerField(blank=True, null=True, default=None)
    propSim = models.IntegerField(blank=True, null=True, default=None)
    maxProf = models.IntegerField(blank=True, null=True, default=None)
    operation = models.CharField(max_length=10, blank=True, null=True, default=None)
    additional = models.CharField(max_length=10, blank=True, null=True, default=None)
    work_activity = models.ForeignKey(WorkActivity, null=True, default=None, on_delete=models.CASCADE)

class AveragesWorkActivity(models.Model):
    average = models.IntegerField()
    student = models.ForeignKey(User, blank=True, related_name='studentWork', null=True, default=None, on_delete=models.CASCADE)
    type_a = models.ForeignKey(WorkActivity, null=True, default=None, on_delete=models.CASCADE)
    active = models.BooleanField(null=True, default=False, blank=True)

class OperationsPractics (models.Model):
    title = models.CharField(max_length=50)
    formula = models.CharField(max_length=225)
    results = models.CharField(max_length=511)
    aux = models.CharField(max_length=225, null=True, blank=True)
    your_results = models.CharField(max_length=225, null=True, blank=True)
    validation = models.CharField(max_length=20, null=True, blank=True)
    users = models.ForeignKey(User, blank=True, related_name='user', default=None, on_delete=models.CASCADE)
    type_c = models.ForeignKey(TypeClass, null=True, default=None, on_delete=models.CASCADE)

class OperationsWorkActivity (models.Model):
    title = models.CharField(max_length=50)
    formula = models.CharField(max_length=225)
    results = models.CharField(max_length=511)
    aux = models.CharField(max_length=225, null=True, blank=True)
    validation = models.CharField(max_length=20, null=True, blank=True)
    your_results = models.CharField(max_length=225, null=True, blank=True)
    users = models.ForeignKey(User, blank=True, related_name='studentOpeWork', default=None, on_delete=models.CASCADE)
    work = models.ForeignKey(WorkActivity, null=True, default=None, on_delete=models.CASCADE)

class Comments(models.Model):
    user_comment = models.ForeignKey(User, blank=True, related_name='users', default=None, on_delete=models.CASCADE)
    time = models.CharField(max_length=50, default=timezone.now().strftime("%a %b %d %Y, %H:%M:%S"))
    text = models.TextField()
    classess = models.ForeignKey(Classes, null=True, default=None, on_delete=models.CASCADE)
    # Funcion para que es puedan guandar archivos de texto grande en la base de datos
    def __str__(self):
        return self.text

program/center/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, PasswordChangeForm
from .models import Profile

# La base de los datos que pide para agragar un nuevo usuario
class RegisterForm(UserCreationForm):
    email = forms.EmailField()
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'username', 'email', 'password1', 'password1']
        labels = {'first_name': 'Fist Name', 'last_name': 'Last Name', 'username': 'No. Control', 'email': 'Email', 'password1': 'Password', 'password1': 'Confirm Password'}
    
    # Funcion para detectar si existe un usuario con el mismo nombre
    def clean_username(self):
        username = self.cleaned_data['username'].lower()
        r = User.objects.filter(username=username)
        if r.count():
            raise  ValidationError("Username already exists")
        return username

    # Funcion para detectar si existe un usurio con el mismo correo electronico
    def clean_email(self):
        email = self.cleaned_data['email'].lower()
        r = User.objects.filter(email=email)
        if r.count():
            raise  ValidationError("Email already exists")
        return email

# La base de los datos que pide para actualizar datos personales
class UserUpdateFrom(forms.ModelForm):
    email = forms.EmailField()
    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email']
        labels = {'username': 'Username', 'first_name': 'Fist Name', 'last_name': 'Last Name', 'email': 'Email'}

# La base de los datos que pide para actualizar la foto del usuario
class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['image']
        
# La base de los datos que pide para actualizar la contraseña 
class PasswordUpdateFrom(PasswordChangeForm):
    class Meta:
        model = User
        fields = ['old_password', 'new_password1', 'new_password2']

program/center/templates/users/login.html
{% extends "static/base.html" %}
{% block title %}
Entrar
{% endblock %}
{% block content %}

<div class="bg-white border rounded py-3 px-5">
  <legend><b>LogIn User</b></legend>
  <form method="POST">
    {% csrf_token %}

    <div class="form-group text-left">
      <label>No. Control / Nombre de usuario:</label>
      <input
        type="text"
        name="username"
        autofocus
        autocapitalize="none"
        autocomplete="username"
        required
        id="id_username"
        class="form-control"
      />
    </div>
    <div class="form-group text-left">
      <label>Contraseña:</label>
      <input
        type="password"
        name="password"
        autocomplete="current-password"
        required
        id="id_password"
        class="form-control"
      />
    </div>

    <div class="from-group">
      <button class="px-4 btn badge-pill btn-info" type="submit">Login</button>
    </div>
  </form>

  <div class="boder-top pt-3">
    <small class="text-muted">
      ¿No tienes una cuenta? <a class="ml-2" href="/register/">Registrate aquí</a>
    </small>
  </div>
</div>
{% endblock %}

program/center/templates/users/logout.html
{% extends "static/base.html" %}
{% block title %} Salir {% endblock %}
{% block content %}
<div class="content-selection">
    <H2>Necesitas regresar</H2>
    <div class="boder-top pt-3">
        <small class="text-muted">
            Necesitas Entrar? <a class="ml-2" href="/login/">Entrar otra ves</a>
        </small>
    </div>
</div>
{% endblock %}

program/center/templates/users/password.html
{% extends "static/base.html" %}
{% block title %} Cambiar contraseña {% endblock %}
{% block content %}
<br>
<div class="row">
    <div class="col-md-4">
        <div class="list-group">
            <button type="button" class="list-group-item list-group-item-action active">Perfil</button>
            <a href="{% url 'profile' %}" class="list-group-item list-group-item-action">Informacion General</a>
            <a href="{% url 'pass' %}" class="list-group-item list-group-item-action">Cambiar contraseña</a>
            <a href="{% url 'deleteUser' %}" onclick="return deleten()" class="list-group-item list-group-item-danger list-group-item-action">Eliminar Usuario</a>
        </div>
    </div>

    <div class="col-md-8">
        <div class="content-section">
            <div class="media">
                <img class="rounded-circle account-img" width="200" height="200" src="{{user.profile.image.url}}">
                <div class="media-body">
                    <h2 class="account-heading">{{ user.username }}</h2>
                    <p class="text-secondary">{{ user.email }}</p>
                </div>
            </div>
        </div>
        <hr>
        <div class="formulation">
            <form method="post">
                {% csrf_token %}
                <fieldset class="from-grup">
                    <legend class="border-botton mb-4">Cambiar contraseña:</legend>
                    <div>
                        <label for="id_old_password">Conraseña actual:</label>
                        <input type="password" class="form-control" name="old_password" autocomplete="current-password" autofocus required id="id_old_password">
                    </div>
        
                    <div>
                        <label for="id_new_password1">Contraseña nueva:</label>
                        <input type="password" class="form-control" name="new_password1" autocomplete="new-password" required id="id_new_password1">
                        <span class="helptext">
                            <ul>
                                <li>Su contraseña no puede ser muy similar a su otra información personal.</li>
                                <li>Su contraseña debe contener al menos 8 caracteres.</li>
                                <li>Su contraseña no puede ser una contraseña de uso común.</li>
                            </ul>
                        </span>
                    </div>
        
                    <div>
                        <label for="id_new_password2">Confirmar nueva contraseña:</label>
                        <input type="password" class="form-control" name="new_password2" autocomplete="new-password" required id="id_new_password2">
                    </div>
                    <br>
                    <div class="from-group">
                        <button class="px-4 btn badge-pill btn-info" type="submit">Actualizar</button>
                    </div>
                </fieldset>
            </form>
        </div>
    </div>
    <script type="text/javascript">
        function deleten() {
          var x = confirm("want delete your user ?");
          if (x)
            return true;
          else
            return false;
        }
      </script>

</div>
<br>
{% endblock %}

program/center/templates/users/profile.html
{% extends "static/base.html" %}
{% block title %} perfil {% endblock %}
{% block content %}
<br>
<div class="row">
    <div class="col-md-4">
        <div class="list-group">
            <button type="button" class="list-group-item list-group-item-action active">Perfil</button>
            <a href="{% url 'profile' %}" class="list-group-item list-group-item-action">Informción General</a>
            <a href="{% url 'pass' %}" class="list-group-item list-group-item-action">Cambiar contraseña</a>
            <a href="{% url 'deleteUser' %}" onclick="return deleten()" class="list-group-item list-group-item-danger list-group-item-action">Eliminar Usuario</a>

        </div>
    </div>

    <div class="col-md-8">
        <div class="content-section">
            <div class="media">
                <img class="rounded-circle account-img" width="200" height="200" src="{{user.profile.image.url}}">
                <div class="media-body">
                    <h2 class="account-heading">{{ user.username }}</h2>
                    <p class="text-secondary">{{ user.email }}</p>
                </div>
            </div>
        </div>
        <hr>
        <div class="formulation">
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="from-group">
                    <legend class="border-botton mb-4">Profile Info</legend>
                    {% if perms.center.add_classes %}
                    <div>
                        <label for="id_username"><b>Nombre de Usuario:</b></label>
                        <input type="text" name="username" maxlength="8" autofocus required id="id_username" class="form-control" value="{{user.username}}" />
                        <span class="helptext">Necesario. 150 caracteres o menos. Letras, dígitos y @./+/-/_ (solamente).</span>
                    </div>
                    {% else %}
                    <input type="hidden" class="form-control" name="username" value="{{user.username}}" requiredid="id_username">
                    {% endif %}
                    
                    <div class="form-group">
                        <label for="id_first_name"><b>Nombre:</b></label>
                        <input type="text" name="first_name" maxlength="150" value="{{user.first_name}}" required id="id_first_name" class="form-control" />
                    </div>

                    <div class="form-group">
                        <label for="id_last_name"><b>Apellidos:</b></label>
                        <input type="text" name="last_name" maxlength="150" required id="id_last_name" class="form-control" value="{{user.last_name}}" />
                    </div>

                    <div class="form-group">
                        <label for="id_email"><b>Email:</b></label>
                        <input type="email" name="email" required id="id_email" class="form-control" value="{{user.email}}">
                    </div>
                    {{p_form}}

                    </fieldset>
                    <br>
                    <div class="from-group">
                        <button class="px-4 btn badge-pill btn-info" type="submit">Update</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
    <script type="text/javascript">
        function deleten() {
          var x = confirm("want delete your user ?");
          if (x)
            return true;
          else
            return false;
        }
      </script>

</div>
<br>

{% endblock %}

program/center/templates/users/register.html
{% extends "static/base.html" %}
{% block title %} Registrar {% endblock %}
{% block content %}

<div class="bg-white border rounded py-3 px-5">
  <legend class="border-botton m4">Registrar Usuario</legend>

  <form method="POST">
    {% csrf_token %}

    <div class="form-group text-left">
      <label>Nombre(s):</label>
      <input
        type="text"
        name="first_name"
        maxlength="150"
        required
        class="form-control"
        placeholder="Ingresa tu nombre..."
      />
    </div>

    <div class="form-group text-left">
      <label>Apellido(s):</label>
      <input
        type="text"
        name="last_name"
        maxlength="150"
        required
        class="form-control"
        placeholder="Ingresa tu apellido..."
      />
    </div>

    <div class="form-group text-left">
      <label>No. Control:</label>
      <input
        type="number"
        name="username"
        min="11111111"
        min="99999999"
        maxlength="8"
        required
        class="form-control"
        placeholder="12345678"
      />
    </div>

    <div class="form-group text-left">
      <label>Email:</label>
      <input
        type="email"
        name="email"
        required
        class="form-control"
        placeholder="Ingresa tu email..."
      />
    </div>

    <div class="form-group text-left">
      <label>Contraseña:</label>
      <input
        type="password"
        class="form-control"
        name="password1"
        autocomplete="new-password"
        required
        placeholder="Ingresa tu contraseña..."
      />
      <small class="form-text text-muted">
        <ul>
          <li>
            Su contraseña no puede ser muy similar a su otra información
            personal.
          </li>
          <li>Su contraseña debe contener al menos 8 caracteres.</li>
          <li>Su contraseña no puede ser una contraseña de uso común.</li>
        </ul>
      </small>
    </div>

    <div class="form-group text-left">
      <label>Verificar Contraseña:</label>
      <input
        type="password"
        class="form-control"
        name="password2"
        autocomplete="new-password"
        required
        placeholder="Repite tu contraseña..."
      />
      <small class="form-text text-muted"
        >Ingrese la misma contraseña que antes, para la verificación.</small
      >
    </div>

    <div class="form-group text-left">
      <label>Tipo de usuario:</label>
      <select class="custom-select" name="accountType" required>
        <option value="student" selected>Estudiante</option>
        <option value="teacher">Maestro</option>
      </select>
    </div>

    <div class="from-group">
      <button class="px-4 btn badge-pill btn-info" type="submit">
        Regístrate
      </button>
    </div>
  </form>
  <div class="boder-top pt-3">
    <small class="text-muted">
      ¿Ya tienes una cuenta? <a class="ml-2" href="{% url 'login' %}">Entrar</a>
    </small>
  </div>
</div>

{% endblock %}